
name: Run CASR
on:
  push:

jobs:
  run-casr:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11' ]
    name: Java ${{ matrix.java }} Run CASR

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 2326dd4ff3adb9cd7ecd0d2937e37b4babe0a1fe
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Install rust and dependencies
      run: | 
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y        
        sudo apt install gdb lsb-release
    - name: Install casr
      run: |
        cargo install casr
    - name: Compile using mvn
      run: |
        mvn clean install -DskipTests
    - name: Run CASR
      run: |
        find . -name '*.java' -exec sh -c 'echo "Processing {}" && timeout 60s casr-java -o {}.casrep -- java  {}' \;
    - name: List any casr reports created
      run: |
        find ./ -name "*.casrep" 
